### ISSUE TITLE
变量 item 重复定义

### ISSUE THREAD

**Issue by XminUnuse** [liub1934/uni-lb-picker#10]
```npm install``` 该插件后，因为无法识别```// #ifdef``` 语句，致使在 mixxins 文件夹下 index.js 中第41行及以下涉及变量 item 时，报错！变量重复定义。

**Comment by liub1934** [comment]
你应该是用了ESLint代码校验吧

**Comment by XminUnuse** [comment]
项目基础是uni-app官方安装模板，```npm install uni-lb-picker ``` 安装后使用 ```npm run dev:mp-weixin``` 命令搭建生产环境时报错，item 变量重复定义，我暂时的解决方法是在文件夹node_modules下拷贝出文件夹lb-picker，放入src目录中使用才成功避免这个错误。

**Comment by liub1934** [comment]
更新到新版本即可，已修复。
