### ISSUE TITLE
支付宝 安卓手机 显示Bug

### ISSUE THREAD

**Issue by tanfei21** [liub1934/uni-lb-picker#2]
支付宝小程序，在安卓手机，真机调试的时候出现Bug，整个picker占了全屏
![image](https://user-images.githubusercontent.com/33183312/79692846-02192c00-829a-11ea-8ced-a1a9edfdcf08.png)

**Comment by liub1934** [comment]
有时间我看以下，可以试下示例中的例子在真机调试的时候是否也会有这张情况。

**Comment by liub1934** [comment]
已修复，取消了对rpx的支持，保持和官方picker一致
