### ISSUE TITLE
你好，getColumnsInfo怎么不顶用呢？

### ISSUE THREAD

**Issue by wlm212** [liub1934/uni-lb-picker#20]
如果是用静态的js变量做数据原，getColumnsInfo是可以的，如果我换成从后端php返回的，默认选中值，getColumnsInfo就不起作用了。获取不到选中的label的值。有没有ajax的设置默认值的例子啊。

**Comment by wlm212** [comment]
onReady () {
		  this.$nextTick(() => {
		    // 此处可以调用getColumnsInfo方法获取默认值的选项信息
		     const info = this.$refs.class.getColumnsInfo(this.value3)
		     console.log('根据value获取的信息：', info)
		     this.label3 = info.item.label
		   ####				
		  })
		}
这个onReady事件 ，设置静态的默认值数据还可以，换成动态的返回数据。他就不行了。

**Comment by liub1934** [comment]
`onReady`里面执行ajax请求获取到值设置this.value3后执行`this.$refs.class.getColumnsInfo(this.value3)`

**Comment by liub1934** [comment]
```javascript
onReady () {
  uni.request({
    success: res => {
      this.value3 = res.data // 根据实际返回数据设置好value3后再使用getColumnsInfo方法
      const info = this.$refs.class.getColumnsInfo(this.value3)
      this.label3 = info.item.label
    }
  })
}
```

**Comment by liub1934** [comment]
参考说明中的`getColumnsInfo注意事项`
```javascript
onReady () {
  this.list = [{ label: '测试', value: 1 }] // 动态设置一个list
  setTimeout(() => {
    const info = that.$refs.picker.getColumnsInfo(xx)
    console.log(info)
  }, 0)
}
```
