### ISSUE TITLE
非联动选择动态加载数据后，value绑定值会重置为初始状态

### ISSUE THREAD

**Issue by abaitangxianjun** [liub1934/uni-lb-picker#23]
作者你好，我在使用该组件非联动选择时，因为业务需要，每改变一列时，会动态请求后面的数据并重新渲染，新的list数组和value的绑定值，我都有处理，比如我当前value数组是[1,0,0,0],请求后的数据变为[2,0,0,0]，但组件更新数据后，会将value数组重置为[0,0,0,0],导致选项全部重置为初始状态。请问有什么解决的办法嘛

**Comment by liub1934** [comment]
这种类型的选择器不太适合动态去渲染数据，建议一次性将数据取到，如果非要按你说的做，可以尝试下下面的方法，请求完成后设置新的list和value，这样会导致触发3次`change`事件。
```javascript
handleChange(item) {
    if (item.change === 'scroll') {
       // setTimeout只是模拟请求
        setTimeout(() => {
            this.list = newList // 设置新的list
            this.value = [2,0,0,0] // 设置新的value，如果设置新的value不起作用可以加个很小的setTimeout延迟
        }, 500)
    }
}
```

**Comment by abaitangxianjun** [comment]
非常感谢你的解答，因为一些需求的原因，我可能无法一次性拿到全部数据，我会尝试使用你的这个办法来解决

**Comment by abaitangxianjun** [comment]
我想我知道可能导致视图重置为初始状态的原因了，可能这与我value数组设置的是数组下标有关，而没有按你组件绑定的应该是list数组对应的value值，我误以为是官方picker-view那种对应的index了，非常抱歉，233
