### ISSUE TITLE
支付宝小程序多层级联动出现无法滑动的情况

### ISSUE THREAD

**Issue by abaitangxianjun** [liub1934/uni-lb-picker#24]
多级联动下拉，在支付宝小程序上 会出现三级或二级，不能滑动的情况，真机和模拟器测试都有该情况发生。
`<lb-picker :value="selects" :list="sameOptions" :level="3" :props="myProps" mode="multiSelector">
<slot></slot>
</lb-picker>`

sameOptions数据：
`[
  {
    id: "10000",
    text: "行业",
    children: [
      {
        id: "10020",
        text: "加油（气）站",
      },
      {
        id: "10100",
        text: "旅店",
      },
      {
        id: "10200",
        text: "未办证留宿住所",
      },
    ],
  },
  {
    id: "20000",
    text: "场所",
    children: [
      {
        id: "20100",
        text: "娱乐服务场所",
        children: [
          {
            id: "20101",
            text: "歌舞娱乐",
          },
          {
            id: "20102",
            text: "游戏电玩",
          },
          {
            id: "20103",
            text: "经营性上网服务场所",
          },
          {
            id: "20104",
            text: "非经营性上网服务场所",
          },
        ],
      },
      {
        id: "20200",
        text: "公共服务场所",
        children: [
          {
            id: "20201",
            text: "桑拿洗浴",
          },
          {
            id: "20202",
            text: "美容美发",
          },
        ],
      },
    ],
  },
  { id: "30000", text: "社会团体组织" },
]`

截图上传不上来，样式大概描述就是三级或二级，整列会颜色变，不能滑动的情况

**Comment by abaitangxianjun** [comment]
> 多级联动下拉，在支付宝小程序上 会出现三级或二级，不能滑动的情况，真机和模拟器测试都有该情况发生。
> `<lb-picker :value="selects" :list="sameOptions" :level="3" :props="myProps" mode="multiSelector"> <slot></slot> </lb-picker>`
> 
> 相同的选项：：
> `[ { id: "10000", text: "行业", children: [ { id: "10020", text: "加油（气）站", }, { id: "10100", text: "旅店", }, { id: "10200", text: "未办证留宿住所", }, ], }, { id: "20000", text: "场所", children: [ { id: "20100", text: "娱乐服务场所", children: [ { id: "20101", text: "歌舞娱乐", }, { id: "20102", text: "游戏电玩", }, { id: "20103", text: "经营性上网服务场所", }, { id: "20104", text: "非经营性上网服务场所", }, ], }, { id: "20200", text: "公共服务场所", children: [ { id: "20201", text: "桑拿洗浴", }, { id: "20202", text: "美容美发", }, ], }, ], }, { id: "30000", text: "社会团体组织" }, ]`
> 
> 截图上传不上来，样式大概描述就是三级或二级，整列会颜色变浅，然后不能滑动

**Comment by liub1934** [comment]
HX3.0.7，支付宝小程序开发者工具1.17.9测试没问题
