### ISSUE TITLE
三级联动，list的值更新时，从第二级开始，children列表值不会更新

### ISSUE THREAD

**Issue by 1260684341** [liub1934/uni-lb-picker#4]
三级联动，list的值更新时，从第二级开始，children列表值不会更新，用的自定义字段，（微信小程序）

**Comment by liub1934** [comment]
> 三级联动，list的值更新时，从第二级开始，children列表值不会更新，用的自定义字段，（微信小程序）

动态更新list数据吗？可以贴一下原list和更新后的新list，我测试下

**Comment by 1260684341** [comment]
> > 三级联动，list 的值更新时，从第二级开始，children 列表值不会更新，用的自定义字段，（微信小程序）
> 
> 动态更新 list 数据吗？可以贴一下原 list 和更新后的新 list，我测试下


[json.zip](https://github.com/liub1934/uni-lb-picker/files/4885042/json.zip)

**Comment by liub1934** [comment]
> > > 三级联动，list 的值更新时，从第二级开始，children 列表值不会更新，用的自定义字段，（微信小程序）
> > 
> > 
> > 动态更新 list 数据吗？可以贴一下原 list 和更新后的新 list，我测试下
> 
> [json.zip](https://github.com/liub1934/uni-lb-picker/files/4885042/json.zip)

可以将`\lb-picker\index.vue`文件中开头几行的`v-show`改成`v-if`，`v-show`会有些问题
