### ISSUE TITLE
二级联动 第二级首次滑动报错，第二次就正常了

### ISSUE THREAD

**Issue by rainbowwj** [liub1934/uni-lb-picker#6]
![微信图片_20200731101513 - 副本](https://user-images.githubusercontent.com/43638625/88994392-d2f36b80-d31a-11ea-9a99-8c9dec1a82fe.png)
![微信图片_20200731101513](https://user-images.githubusercontent.com/43638625/88994395-d4bd2f00-d31a-11ea-94a6-dbe6a3c525f5.png)
![微信图片_20200731101310](https://user-images.githubusercontent.com/43638625/88994400-d4bd2f00-d31a-11ea-84bb-3f69ef1e214a.png)
![微信图片_20200731101426](https://user-images.githubusercontent.com/43638625/88994401-d5ee5c00-d31a-11ea-840c-4c8be14f43ec.png)

**Comment by liub1934** [comment]
可以贴下数据吗，如果是敏感数据，可以把中文随便改改，其他没用的字段删掉，只保留选择器关键的几个字段。

**Comment by rainbowwj** [comment]
{
    "status": 1,
    "msg": "请求成功",
    "data": {
        "list": [
            {
                "id": "18",
                "title": "学习",
                "type": "0",
                "array": [
                    {
                        "id": "19",
                        "title": "学习",
                        "type": "18",
                        "baseId": "19"
                    }
                ]
            },
            {
                "id": "4",
                "title": "语文",
                "type": "0",
                "array": [
                    {
                        "id": "12",
                        "title": "选修1",
                        "type": "4",
                        "baseId": "12"
                    },
                    {
                        "id": "15",
                        "title": "选修2",
                        "type": "4",
                        "baseId": "15"
                    },
                    {
                        "id": "17",
                        "title": "选修3",
                        "type": "4",
                        "baseId": "17"
                    }
                ]
            },
            {
                "id": "1",
                "title": "数学",
                "type": "0",
                "array": [
                    {
                        "id": "5",
                        "title": "选修1",
                        "type": "1",
                        "baseId": "5"
                    },
                    {
                        "id": "6",
                        "title": "选修2",
                        "type": "1",
                        "baseId": "6"
                    },
                    {
                        "id": "7",
                        "title": "选修3",
                        "type": "1",
                        "baseId": "7"
                    },
                    {
                        "id": "16",
                        "title": "选修4",
                        "type": "1",
                        "baseId": "16"
                    },
                    {
                        "id": "24",
                        "title": "选修5",
                        "type": "1",
                        "baseId": "24"
                    },
                    {
                        "id": "27",
                        "title": "选修6",
                        "type": "1",
                        "baseId": "27"
                    },
                    {
                        "id": "28",
                        "title": "选修7",
                        "type": "1",
                        "baseId": "28"
                    }
                ]
            }
        ]
    }
}
这种类型的  我改了一些title

**Comment by liub1934** [comment]
我测试了下没有你说的问题，不知道具体你那儿是怎么用的
```html
<template>
  <view>
    <button @tap="handleTap">点我弹出2级联动选择器</button>
    <lb-picker ref="picker"
      v-model="value"
      mode="multiSelector"
      :list="list"
      :level="2"
      :props="props">
    </lb-picker>
  </view>
</template>

<script>
export default {
  data () {
    return {
      value: [],
      props: {
        label: 'title',
        value: 'id',
        children: 'array'
      },
      list: [
        {
          id: '18',
          title: '学习',
          type: '0',
          test: null,
          array: [
            {
              id: '19',
              title: '学习',
              type: '18',
              baseId: '19'
            }
          ]
        },
        {
          id: '4',
          title: '语文',
          type: '0',
          array: [
            {
              id: '12',
              title: '选修1',
              type: '4',
              baseId: '12'
            },
            {
              id: '15',
              title: '选修2',
              type: '4',
              baseId: '15'
            },
            {
              id: '17',
              title: '选修3',
              type: '4',
              baseId: '17'
            }
          ]
        },
        {
          id: '1',
          title: '数学',
          type: '0',
          array: [
            {
              id: '5',
              title: '选修1',
              type: '1',
              baseId: '5'
            },
            {
              id: '6',
              title: '选修2',
              type: '1',
              baseId: '6'
            },
            {
              id: '7',
              title: '选修3',
              type: '1',
              baseId: '7'
            },
            {
              id: '16',
              title: '选修4',
              type: '1',
              baseId: '16'
            },
            {
              id: '24',
              title: '选修5',
              type: '1',
              baseId: '24'
            },
            {
              id: '27',
              title: '选修6',
              type: '1',
              baseId: '27'
            },
            {
              id: '28',
              title: '选修7',
              type: '1',
              baseId: '28'
            }
          ]
        }
      ]
    }
  },
  methods: {
    handleTap () {
      this.$refs.picker.show()
    }
  }
}
</script>
```

**Comment by liub1934** [comment]
上面测试的是微信的，百度的好像是有点问题，下午我具体看看。

**Comment by rainbowwj** [comment]
我使用的是百度小程序  就是会有这个问题  好的 麻烦你了

**Comment by liub1934** [comment]
不知道是百度的问题 还是uni的问题，我用原始的`picker-view`试了下，也会存在这个问题，就算滚动到最后或者第一项的时候继续滚动任然会一直触发`change`，不知道谁的BUG，明天社区论坛提个BUG。
```html
<template>
  <view>
    <picker-view :indicator-style="indicatorStyle"
      :value="value"
      @change="bindChange">
      <picker-view-column>
        <view class="item"
          v-for="(item, index) in list1"
          :key="index">{{
          item.title
        }}</view>
      </picker-view-column>
      <picker-view-column>
        <view class="item"
          v-for="(item, index) in list2"
          :key="index">{{
          item.title
        }}</view>
      </picker-view-column>
    </picker-view>
  </view>
</template>

<script>
export default {
  data () {
    return {
      list1: [
        {
          id: '18',
          title: '学习'
        },
        {
          id: '4',
          title: '语文'
        }
      ],
      list2: [
        {
          id: '19',
          title: '自学'
				}
      ],
      value: [0, 0],
      indicatorStyle: `height: ${Math.round(
        uni.getSystemInfoSync().screenWidth / (750 / 100)
      )}px;`
    }
  },
  methods: {
    bindChange (e) {
			console.log(e)
      this.value = e.detail.value
      if (this.value[0]) {
        this.list2 = [
          {
            id: '12',
            title: '选修1'
          },
          {
            id: '15',
            title: '选修2'
          },
          {
            id: '17',
            title: '选修3'
          }
        ]
      } else {
        this.list2 = [
          {
            id: '19',
            title: '自学',
            type: '18'
          }
        ]
      }
    }
  }
}
</script>

<style>
picker-view {
  width: 100%;
  height: 600rpx;
  margin-top: 20rpx;
}
.item {
  line-height: 100rpx;
  text-align: center;
}
</style>

```

**Comment by liub1934** [comment]
暂时可以先在`multi-selector-picker.vue`54行，加个判断，避免报错情况：

```javascript
if (columnIndex > -1 && valueIndex > -1) {
    this.setPickerChange(pickerValue, valueIndex, columnIndex)
}
```

**Comment by rainbowwj** [comment]
加上是不报错 可是就是有bug  首次滑动二级不生效  需要再次滑动才能选择上

**Comment by liub1934** [comment]
> 加上是不报错 可是就是有bug 首次滑动二级不生效 需要再次滑动才能选择上

百度小程序的问题，已经提交官方了，等百度那边修复吧
[https://smartprogram.baidu.com/forum/topic/show/117329](https://smartprogram.baidu.com/forum/topic/show/117329)

**Comment by rainbowwj** [comment]
就是现在在测试的时候 那个二级联动是显示数据的，但是一手机预览就会显示暂无数据，我测试了数据是存在的，但是在弹出框中就显示暂无数据

**Comment by liub1934** [comment]
> 就是现在在测试的时候 那个二级联动是显示数据的，但是一手机预览就会显示暂无数据，我测试了数据是存在的，但是在弹出框中就显示暂无数据

开发者工具上预览都是正常的，真机我这边没有appid无法测试。。。
