### ISSUE TITLE
在微信小程序中展示正常，在支付宝小程序展示空白

### ISSUE THREAD

**Issue by kennsand** [liub1934/uni-lb-picker#7]
![image](https://user-images.githubusercontent.com/22880635/90113087-6a2cda00-dd83-11ea-8947-d9263c0fb995.png)

**Comment by liub1934** [comment]
运行下示例看看，我本地测试了下是正常的。
![image](https://user-images.githubusercontent.com/29849550/90114031-bc222f80-dd84-11ea-926c-071fa00dac56.png)

**Comment by kennsand** [comment]
> 运行下示例看看，我本地测试了下是正常的。
> ![image](https://user-images.githubusercontent.com/29849550/90114031-bc222f80-dd84-11ea-926c-071fa00dac56.png)

已解决：更新最新代码后解决
