### ISSUE TITLE
支付宝小程序案例点击确定多几次就会出现

### ISSUE THREAD

**Issue by kennsand** [liub1934/uni-lb-picker#8]
![image](https://user-images.githubusercontent.com/22880635/90305605-1ba04c80-def7-11ea-801c-d7cc22b049b6.png)

**Comment by liub1934** [comment]
不影响 可以忽略

**Comment by kennsand** [comment]
> 不影响 可以忽略

![image](https://user-images.githubusercontent.com/22880635/90306022-7b005b80-defb-11ea-9efa-f8bf58f6ed3c.png)
第二个地区选择点击确定会一直循环报错，导致卡死

**Comment by kennsand** [comment]
> 不影响 可以忽略
![image](https://user-images.githubusercontent.com/22880635/90306075-28736f00-defc-11ea-8dcb-b833e4cb34b6.png)

第二个地区选择点击确定会一直循环报错，导致卡死

**Comment by liub1934** [comment]
稍后更新一版 将这个错误去掉

**Comment by liub1934** [comment]
更新新版本试试
