### ISSUE TITLE
报错信息："TypeError: Cannot set property 'isConfirmChange' of undefined"

### ISSUE THREAD

**Issue by liucan25011** [liub1934/uni-lb-picker#9]
您好，我们后台返回的省市区，我只要使用后台返回的数组就报这个错误，后台返回的数组没问题，我测试截取数组里里面的前几个数组对象赋值给list也没问题，就是使用整个的就会报这个错误，而且很诡异的问题是，list我使用死数据后，后台返回的数组我获取过来任何地方都没用使用，就存在data里都报错，注销掉data里的返回数据还是使用死数据就不报错了

**使用的是uni+微信小程序编程报错**

list数组链接：
https://app.yinxiang.com/fx/d2ced27f-a81f-4123-886c-933c11422312

**报错图片链接**
https://app.yinxiang.com/fx/684c62d8-47a8-4407-b322-6ab4a6244f92

**我的代码：**

<lb-picker ref="picker1" :props="myProps"  v-model="pickervalue"  mode="multiSelector" :list="list" :level="2" 
@confirm="handleConfirm">
</lb-picker>

data() {
	return {
                list: [ ] ,
		myProps: {
			label: 'name',
			value: 'id',
			children: 'children'
			},
	}
}

methods:{
// 所有城市
async selectchinamap() {
	var res = await this.$baseAPI.request('/api/user/chinaMap/selectChinaMap')
	if (res.status == 200) {
		this.list = res.data
	}
  },
}

**Comment by liub1934** [comment]
将`index.vue`中294行开始的
```javascript
this.$nextTick(() => {
  this.$refs[this.mode].isConfirmChange = true
})
```

改成下面的即可

```javascript
this.$refs[this.mode].isConfirmChange = true
```

**Comment by liucan25011** [comment]
handleChange ({ value, item, index, change }) {
      this.picker.value = value
      this.picker.item = item
      this.picker.index = index
      this.picker.change = change
      this.picker.dataset = this.dataset || {}
      this.$emit('change', this.picker)
      this.$refs[this.mode].isConfirmChange = true
    },

改过了，没有效果，还是报同样错误

**Comment by liub1934** [comment]
[294行](https://github.com/liub1934/uni-lb-picker/blob/master/components/lb-picker/index.vue#L294)

**Comment by liucan25011** [comment]
谢谢大佬，解决了，辛苦了，撒花
